---
- name: ensure a list of packages installed
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - git
    - python3
    - epel-release
    - nginx
    - docker

- name: install pip packages
  pip:
    name: "{{ pip_packages }}"
    executable: pip3
  vars:
    pip_packages:
    - boto3

- name: Ensure docker deamon is running
  service:
    name: docker
    state: started
  become: true