---
- hosts: all
  user: centos
  vars_files:
    - group_vars/vars.yml
  become: yes
  tasks:
    - name: ensure a list of packages installed
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - git
        - python3
    - name: install pip packages
      pip:
        name: "{{ pip_packages }}"
        executable: pip3
      vars:
        pip_packages:
        - boto3
    - name: Ensure group "linecountrunner" exists
      group:
        name: linecountrunner
        state: present
    - name: Ensure user "linecountrunner" exists
      user:
        name: linecountrunner
        state: present
        group: linecountrunner
    - name: "Clone repo"
      git:
        repo: 'https://github.com/odemeulder/linecount.git'
        dest: /home/linecount
    - name: Recursively change ownership of a directory
      file:
        path: /home/linecount
        state: directory
        recurse: yes
        owner: linecountrunner
        group: linecountrunner